substitutions:
  name: esphome-web-2cc050
  friendly_name: Amped-ESP32-S3-Plus-02
  task_stack_in_psram: "true" # important to disable this for non-S3 model

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2026.1.4
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"

      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"  # TLS1.3 support isn't enabled by default in IDF 5.1.5

# Enable logging
logger:
  level: DEBUG
  
wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  ap:
    ssid: "$name Hotspot"
    password: !secret esphome_ap_password

captive_portal:

### Optional if you want ethernet (then remove above wifi config)
#ethernet:
#  type: W5500
#  clk_pin: GPIO12
#  mosi_pin: GPIO11
#  miso_pin: GPIO13
#  cs_pin: GPIO10
#  interrupt_pin: GPIO6
#  reset_pin: GPIO5

# Allow Over-The-Air updates
ota:
  platform: esphome
  password: !secret esphome_ota_password

# Enable Home Assistant API
api:

psram:
  mode: octal
  speed: 80MHz

network:
  enable_ipv6: true

external_components:
  - source: github://sonocotta/esphome-pcm5122
    components: [ pcm5122 ]
    refresh: 24h

  - source: github://c-MM/esphome-snapclient
    components: [ snapclient ]
    refresh: 24h

i2c:
  sda: GPIO18 
  scl: GPIO8
  frequency: 400kHz
  scan: True
  timeout: 100us

audio_dac:
  - platform: pcm5122
    id: pcm5122_dac
    address: 0x4D           # I2C address of the DAC, it is 0x4C n the HiFi-ESP32 Rev H, and 0x4D on the rev H1+
    volume_max: 0dB         # maximum volume range 0dB, can go up to +24dB
    volume_min: -60dB       # minimum volume range -60dB, can go down to -103dB
    analog_gain: -6dB       # or -6Db for 1V RMS output, default is 0dB = 2V RMS output
    mixer_mode: STEREO      # MIXER MODE: STEREO, STEREO_INVERSE, LEFT, RIGHT

i2s_audio:
  i2s_lrclk_pin: GPIO15
  i2s_bclk_pin: GPIO14

### Snapclient component is a work in progress, not yet ready for production use
# More details:
# https://github.com/c-MM/esphome-snapclient/
# https://github.com/esphome/esphome/pull/8350
snapclient:
  hostname: 192.168.1.49   # at this time auto-discovery does not work, so you need to specify the server IP address
  port: 1704               # default port, no need to change unless you have changed it on the server side
  name: ${friendly_name}     # this is the name that will appear in the snapcast clients list
  i2s_dout_pin: GPIO16     # I2S data out pin
  webserver_port: 8080     # start webserver for snapclient controls

### RGB light config (if installed)
light:
  - platform: esp32_rmt_led_strip
    id: rgb_front_led
    name: "${friendly_name} LED"
    rgb_order: GRB
    pin: GPIO21
    num_leds: 1
    chipset: ws2812
    default_transition_length: 0s

### IR reader config (if installed). Add your own IR codes as needed
remote_receiver:
  pin: 
    number: GPIO07
    inverted: true
    mode:
      input: true
  dump: all

switch:
  - platform: pcm5122
    enable_dac:
      name: Enable DAC
      id: enable_dac
      restore_mode: ALWAYS_ON

  - platform: gpio
    icon: "mdi:speaker"
    name: Enable AMP
    id: enable_amp
    pin:
      number: GPIO17
    restore_mode: ALWAYS_ON

button:
  - platform: restart
    id: restart_btn
    name: "${friendly_name} REBOOT"

### Optional settings for OLED screen 
# prerequisites:
font:
  - file:
      type: gfonts
      family: Roboto
      weight: regular
    id: roboto_medium
    size: 32
    glyphs: [' ', ':', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

spi:
  clk_pin: GPIO12
  mosi_pin: GPIO11
  miso_pin: GPIO13

time:
  - platform: sntp
    id: sntp_time

### Example display configuration, showing the current playback state
display:
  - platform: ssd1306_spi
    model: SH1106 128x64
    cs_pin: GPIO47
    dc_pin: GPIO38
    reset_pin: GPIO48
    update_interval: 1s
    lambda: |-
        // display clock
        auto hours = id(sntp_time).now().hour;
        auto minutes = id(sntp_time).now().minute;
        auto seconds = id(sntp_time).now().second;
        auto dot = seconds % 2 == 0 ? " " : ":";
        it.printf(64, 32, id(roboto_medium), TextAlign::CENTER, "%d%s%02d", hours, dot ,minutes);